version: 0.2
 
phases:
  install:
    runtime-versions:
      python: 3.x  # Optional, can be removed if not needed
    commands:
      - echo No dependencies to install.
  build:
    commands:
      - echo "Running Terraform commands..."
      - terraform init
      - terraform apply -auto-approve
