version: 0.2
 
phases:
  install:
    commands:
      - echo Installing Terraform...
      - curl -LO https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
      - unzip terraform_1.5.0_linux_amd64.zip
      - sudo mv terraform /usr/local/bin/
      - terraform --version
  build:
    commands:
      - echo "Running Terraform commands..."
      - terraform init
      - terraform apply -auto-approve
